services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: momo_fraud
      POSTGRES_USER: momo_admin
      POSTGRES_PASSWORD: change_this_password_123!
    ports:
      - "5432:5432"
    volumes:
      - momo_fraud_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U momo_admin -d momo_fraud"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  momo_fraud_pgdata:
